## 1.1 Creating a Vector

### Problem

You need to create a vector.

### Solution

Use NumPy to create a one-dimensional array

In [1]:
# Load library
import numpy as np
# Create a vector as a row
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([[1],[2],[3]])


In [2]:
vector_row

array([1, 2, 3])

In [3]:
vector_column

array([[1],
       [2],
       [3]])

## 1.2 Creating a Matrix

### Problem

You need to create a matrix.

### Solution

Use NumPy to create a two-dimensional array

In [4]:
# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])


In [5]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

## 1.3 Creating a Sparse Matrix

### Problem

Given data with very few non zero values, you want to efficiently represent it.

### Solution

Create a sparse matrix:

In [6]:
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [7]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

In [8]:
print(matrix_sparse) 

  (1, 1)	1
  (2, 0)	3


## 1.4 Selecting Elements

### Problem

You need to select one or more elements in a vector or matrix.


### Solution

NumPy’s arrays make that easy:

In [9]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [10]:
vector[2]

3

In [11]:
matrix[0][1]

2

In [12]:
matrix[0]

array([1, 2, 3])

In [13]:
matrix[0,1]

2

## 1.5 Describing a Matrix

### Problem

You want to describe the shape, size, and dimensions of the matrix.

### Solution

Use shape, size, and ndim:

In [14]:
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [15]:
# View number of rows and columns
matrix.shape

(3, 4)

In [16]:
# View number of elements (rows * columns)
matrix.size

12

In [17]:
# View number of dimensions
matrix.ndim

2

## 1.6 Applying Operations to Elements

### Problem

You want to apply some function to multiple elements in an array.

### Solution

Use NumPy’s vectorize:


In [18]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3,10],
                   [4, 5, 6,10],
                   [7, 8, 9,10]])
# Create function that adds 100 to something
add_100 = lambda i: i + 12
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[13, 14, 15, 22],
       [16, 17, 18, 22],
       [19, 20, 21, 22]])

In [19]:
matrix + 12

array([[13, 14, 15, 22],
       [16, 17, 18, 22],
       [19, 20, 21, 22]])

## 1.7 Finding the Maximum and Minimum Values

### Problem

You need to find the maximum or minimum value in an array.

### Solution

Use NumPy’s max and min:

In [20]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [21]:
# Return maximum element
np.max(matrix)

9

In [22]:
# Return minimum element
np.min(matrix)

1

In [23]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [24]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

## 1.8 Calculating the Average, Variance, and Standard Deviation

### Problem

You want to calculate some descriptive statistics about an array.

### Solution

Use NumPy’s mean, var, and std:

In [25]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


In [26]:
# Return mean
np.mean(matrix)

5.0

In [27]:
# Return variance
np.var(matrix)

6.666666666666667

In [28]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [29]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

## 1.9 Reshaping Arrays
### Problem
You want to change the shape (number of rows and columns) of an array without changing the element values.
### Solution
Use NumPy’s reshape:

In [30]:
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [31]:
matrix.reshape(1, -1)# one row as many columns

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [32]:
matrix.reshape(12)# return a 1D array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 1.10 Transposing a Vector or Matrix
### Problem
You need to transpose a vector or matrix.
### Solution
Use the T method:

In [33]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 1.11 Flattening a Matrix
### Problem
You need to transform a matrix into a one-dimensional array.
### Solution
Use flatten:

In [35]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1.12 Finding the Rank of a Matrix
### Problem
You need to know the rank of a matrix.
### Solution
Use NumPy’s linear algebra method matrix_rank:

In [36]:
# Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

## 1.13 Calculating the Determinant
### Problem
You need to know the determinant of a matrix
### Solution
Use NumPy’s linear algebra method det:

In [37]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
# Return determinant of matrix
np.linalg.det(matrix)

0.0

## 1.14 Getting the Diagonal of a Matrix
### Problem
You need to get the diagonal elements of a matrix.
### Solution
Use diagonal

In [38]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [39]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [40]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

## 1.15 Calculating the Trace of a Matrix
### Problem
You need to calculate the trace of a matrix.
### Solution
Use trace:

In [41]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
# Return trace
matrix.trace()

14

In [42]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

## 1.16 Finding Eigenvalues and Eigenvectors
### Problem
You need to find the eigenvalues and eigenvectors of a square matrix.
### Solution
Use NumPy’s linalg.eig:

In [43]:
# Create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [44]:
# View eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [45]:

# View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

## 1.17 Calculating Dot Products
### Problem
You need to calculate the dot product of two vectors.
### Solution
Use NumPy’s dot:

In [46]:
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# Calculate dot product
np.dot(vector_a, vector_b)

32

## 1.18 Adding and Subtracting Matrices
### Problem
You want to add or subtract two matrices.
### Solution
Use NumPy’s add and subtract:

In [47]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

In [48]:
# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [49]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [50]:
# Add two matrices
matrix_a + matrix_b


array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

## 1.19 Multiplying Matrices
### Problem
You want to multiply two matrices.
### Solution
Use NumPy’s dot:

In [51]:
# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])
# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])
# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [52]:
# Multiply two matrices
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [53]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

## 1.20 Inverting a Matrix
### Problem
You want to calculate the inverse of a square matrix.
### Solution
Use NumPy’s linear algebra inv method:

In [54]:
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

## 1.21 Generating Random Values
### Problem
You want to generate pseudorandom values.
### Solution
Use NumPy’s random:

In [55]:
# Set seed
np.random.seed(0)
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [56]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [57]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [58]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [59]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])